### ISSUE TITLE
IBDesignable properties not showing up on interface builder

### ISSUE THREAD

**Issue by aftabaig** [motylevm/skstylekit#1]
I have an existing project (in obj-c) to which I added style kit.
I set the custom class of one of my buttons to SKButton.
But the style properties are not visible on the label's attributes inspector.
Is there anything I am missing?

**Comment by motylevm** [comment]
First of all check that your custom class module has been set right:

![custombutton](https://cloud.githubusercontent.com/assets/5831773/21001339/cccd30fa-bd30-11e6-8d50-068fe3094556.png)

In attributes inspector you should be able to see:

![button2](https://cloud.githubusercontent.com/assets/5831773/21001395/20bc7ce8-bd31-11e6-9b6e-1ed021b085aa.png)

Sorry for late answer, hope it'll help.
