### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by JanC** [motylevm/skstylekit#6]
Hi,
could you add more examples on how to use the style programatically. It's not obvious what the `StyleName` in  `let style = StyleKit.style(withName: "StyleName")` is

cheers

**Comment by motylevm** [comment]
Hello and thanks for your feedback!
I've updated documentation to make it clear what "StyleName" really refers to.

**Comment by Monserg** [comment]
You are a magician!

**Comment by JanC** [comment]
thanks!
