### ISSUE TITLE
Swift 4, Xcode 9.2, Cocoapods 1..4.0 - 13 warnings

### ISSUE THREAD

**Issue by Monserg** [motylevm/skstylekit#7]
Hi.
I'm try to install you framework to test App.
And have 13 warnings - needs fix issues for new Swift 4 syntax:
<img width="578" alt="2018-02-03 14 13 34" src="https://user-images.githubusercontent.com/3746830/35767044-e3c29eea-08ec-11e8-8eb5-4edd25f8eeaa.png">
How can I fix this?
Thanks.

**Comment by motylevm** [comment]
Hello, thank you for your feedback!
Just ignore these warnings they'll be solved in upcoming release!

**Comment by Monserg** [comment]
Ok, I waiting...
Today I fix all of them & send you for check:
[SKStyleKit.zip](https://github.com/motylevm/skstylekit/files/1692103/SKStyleKit.zip)

**Comment by Monserg** [comment]
I like your work!
