### ISSUE TITLE
Swift 4.2 compilation error

### ISSUE THREAD

**Issue by JanC** [motylevm/skstylekit#8]
Hi,
when I compile the project with Xcode 10 (beta 4) and Swift 4.2, I get the error 

```
SKActivityIndicatorView.swift:37:14: Property 'style' with type 'SKStyle?' cannot override a property with type 'UIActivityIndicatorViewStyle'
```
A property cannot be overridden with a different type

**Comment by motylevm** [comment]
Hello, thank you for your feedback!
Try Swift 4.2 branch.
